description = "前回開発の引継書(HANDOVER.md)を読み込み、開発を再開する"

prompt = """

# タスク: プロジェクトの開発再開

あなたのタスクは@HANDOVER.mdの中身をすべて読みこみ、深く理解することです。またこれは前回までのGeminiCLIの開発の引継書であるため、引継書にある通り引き続き開発を行ってください。

## 手順

1. **`HANDOVER.md` の解析**:
  内容を確認してください。

2. **ユーザへの確認**:
  **重要:** いきなり開発を開始せず、前回までの開発の要約と、今回行う開発の予定をユーザに提示し、実行の許可を求めてください。　

3. **開発の再開**:
  ユーザが承認したら、開発を再開してください。

もし `HANDOVER.md` が存在しない場合はその旨をユーザに報告し、指示を仰いで下さい。
それではタスクを開始してください。

"""
